Skeptic
cambridgeconsultants/grease pull request #2
Opened 2018-05-16 21:31 UTC by dtwood

2018-05-17 06:16 UTC, bjorn3 requested changes

2018-05-17 06:16 UTC, bjorn3 commented on Cargo.toml
> +skeptic = "0.13"
Missing trailing newline

2018-05-17 06:16 UTC, bjorn3 commented on README.md.skt.md
> +```
Missing trailing newline

2018-05-18 09:35 UTC, merged

2018-05-18 09:36 UTC, jonathanpallant commented
I'd not come across `skeptic` before - thanks for this PR!